obj-$(CONFIG_ATHEROS_RATE_AMRR)		+= ath_rate/amrr/
obj-$(CONFIG_ATHEROS_RATE_MINSTREL)	+= ath_rate/minstrel/
obj-$(CONFIG_ATHEROS_RATE_ONOE)		+= ath_rate/onoe/
obj-$(CONFIG_ATHEROS_RATE_SAMPLE)	+= ath_rate/sample/
obj-$(CONFIG_ATHEROS)			+= ath/ ath_hal/ net80211/

ifeq ($(CONFIG_ATHEROS_DEBUG),y)
EXTRA_CFLAGS += -DAR_DEBUG -DIEEE80211_DEBUG
endif
