#
# Makefile for the Minstrel rate control algorithm.
#
# $Id: //depot/sw/linuxsrc/src/802_11/madwifi/madwifi/ath_rate/minstrel/Makefile.kernel#1 $
#

src ?= .
srctree ?= .

TOP = $(srctree)/$(src)/../..

include $(TOP)/BuildCaps.inc

ATH=	$(TOP)/ath
COMPAT=	$(TOP)/include
HAL=	$(TOP)/ath_hal

INCS = -include $(COMPAT)/compat.h -I$(COMPAT)
INCS += -I$(TOP) -I$(ATH) -I$(HAL)
EXTRA_CFLAGS += $(INCS) $(COPTS)

obj-$(CONFIG_ATHEROS) += ath_rate_minstrel.o
ath_rate_minstrel-objs	:= minstrel.o
